apiVersion: v1
kind: Service
metadata:
  labels:
    webserver: backend
  name: rhel9-graphana
  namespace: summit-connect
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    port: 8080
    targetPort: 44322
  selector:
    webserver: backend
