apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: L2Advertisement
  metadata:
    name: l2-adv-sample1
    namespace: metallb-system
  spec:
    ipAddressPools:
    - ip-addresspool-summit-connect
kind: List
metadata:
  resourceVersion: ""
